#!/bin/bash

ssh_options="-o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=1 -o ConnectTimeout=30 -t -t "
user='ubuntu'
get_script="wget http://git.io/vWVpZ --no-check-certificate -O openvpn-autoinstall.sh"
run_script="sudo bash ./openvpn-autoinstall.sh"
remote_path="\$HOME/aws_vpn.ovpn"

gray='\033[0m'
green='\033[00;32m'
red='\033[01;31m'
white='\033[01;37m'
yellow='\033[00;33m'


function usage {
  # ---------------------------------------------------------------------------
	echo -e "${white}DESCRIPTION:\n $gray        $(basename $0) - AWS OpenVPN Deployment Tool.\n\t Project found at https://github.com/ttlequals0/autovpn"
  echo -e "${white}USAGE:\n $gray ACTION\t [OPTIONS] 
  $white-C$gray\t Create VPN endpoint.
  $white-D$gray\t Delete keypair from region.  
  $white-G$gray\t Generate new keypair.
  $white-S$gray\t Get all running instances in a given region.
  $white-T$gray\t Terminate a OpenVPN endpoint.
  $white-a$gray\t Specify a custom ami.*
  $white-h$gray\t Displays this message.
  $white-i$gray\t AWS Instance type (Optional, Default is t2.micro)\n\t t2.nano t2.micro t2.small t2.medium t2.large **
  $white-k$gray\t Specify the name of AWS keypair.
  $white-r$gray\t Specify AWS Region.\n\t us-east-1 us-west-1 us-west-2 eu-west-1 eu-central-1\n\t\
 ap-southeast-1 ap-northeast-1 ap-northeast-2 sa-east-1\n\t ap-southeast-2.
  $white-u$gray\t Specify custom ssh user.***
  $white-z$gray\t Specify instance id." 
  echo -e "${white}EXAMPLES:\n $gray Create OpenVPN endpoint: \n\tautovpn -C -r us-east-1 -k macbook\n\
  Generate keypar in a region.\n\tautovpn -G -r us-east-1\n  Get running instances\n\tautovpn -S -r us-west-1\n\
  Terminate OpenVPN endpoint\n\tautovpn -T -r us-west-1 -z i-b933e00c\n  Using custom options\n\
  \tautovpn -C -r us-east-1 -k macbook -a ami-fce3c696 -u ec2_user -i m3.medium"
  echo -e "${white}NOTES:\n $gray* - Customs ami may be needed if changing instance type.\n $gray** - In reality any\
  instance size can be given but the t2.micro\n is more than enough.\n\
 $gray*** - Custom user might be need if using a custom ami."
}


bail ()
{
	echo -e "${red}Error code $1"
  usage
	exit 
}


failed ()
{
  if [ "$1" == "1" ]; then 
  echo -e "${red}Key already exists in AWS\n"
  elif [ "$1" == "2" ]; then 
  echo -e "${red}\nFailed to terminate instance"
  elif [ "$1" == "3" ]; then 
  echo -e "${red}\nFailed to delete keypair"  
  fi
  tput sgr0 
  exit 
}

if ( ! getopts "CDGSTk:a:hr:i:u:z:" opt); then
	usage;
	exit 1;
fi

while getopts ":CDGSTk:a:hr:i:u:z:" opt; do
  case $opt in
    C) Cflag="defined" ;;
    D) Dflag="defined" ;;        
    G) Gflag="defined" ;;
    S) Sflag="defined" ;; 
    T) Tflag="defined" ;;
    a) custom_ami="$OPTARG" ;;                  
    h) usage && exit 0 ;; 
    i) instance_type="$OPTARG" ;;       	
    k) kflag="defined"; keyname="$OPTARG" ;;
    r) rflag="defined"
      if [ "$OPTARG" == "us-east-1" ]; then region="us-east-1"; ami="ami-d05e75b8"
      elif [ "$OPTARG" == "us-west-1" ]; then region="us-west-1"; ami="ami-06116566"
      elif [ "$OPTARG" == "us-west-2" ]; then region="us-west-2"; ami="ami-9abea4fb"
      elif [ "$OPTARG" == "eu-west-1" ]; then region="eu-west-1"; ami="ami-f95ef58a"
      elif [ "$OPTARG" == "eu-central-1" ]; then region="eu-central-1"; ami="ami-87564feb"  
      elif [ "$OPTARG" == "ap-northeast-1" ]; then region="ap-northeast-1"; ami="ami-a21529cc"
      elif [ "$OPTARG" == "ap-northeast-2" ]; then region="ap-northeast-2"; ami="ami-09dc1267"
      elif [ "$OPTARG" == "ap-southeast-1" ]; then region="ap-southeast-1"; ami="ami-25c00c46"
      elif [ "$OPTARG" == "ap-southeast-2" ]; then region="ap-southeast-2"; ami="ami-6c14310f" 
      elif [ "$OPTARG" == "sa-east-1" ]; then region="sa-east-1"; ami="ami-0fb83963"
      else echo "Not a valid region"; bail 3; fi                                               
      ;; 
    u) custom_user="$OPTARG" ;;       
    z) zflag="defined"; term_ids="$OPTARG" ;;     
    \?) echo "Invalid option: -$OPTARG" >&2 ; bail 1 ;;
    :)  echo "Option -$OPTARG requires an argument." >&2 ; bail 2      
  esac
done

if [[ -z "$instance_type" ]]; then 	instance_type="t2.micro"; fi
if [[ -n "$custom_ami" ]]; then  ami="$custom_ami"; fi
if [[ -n "$custom_user" ]]; then  user="$custom_user"; fi

local_path="$(pwd)/${region}_aws_vpn.ovpn"


if [ -n "$Cflag" ] && [ -n "$rflag" ] && [ -n "$kflag"  ] ; then
  echo "Creating ec2 instance in $region. This can take some time..."
  instance_ip=$(python create_ec2.py "$keyname" "$instance_type" "$region" "$ami")
  [[ $instance_ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] || bail 4
  echo -e "${green}Instance has been created $instance_ip"
  echo -e "${yellow}Giving new instance some time to fully boot up..."
  while [ "$status" != "0" ] 
    do 
	   echo -e "${yellow}$instance_ip is still booting..."
	   sleep 15
	   ssh-keyscan $instance_ip 2>&1 | grep -v "^$" > /dev/null
	   status=$?
  done
  echo -e "${white}Setting up VPN on $instance_ip"
  ssh $ssh_options "$user"@$instance_ip "$get_script && $run_script" || bail 5
  scp $user@$instance_ip:"$remote_path" "$local_path" || bail 6
  echo -e "${green}OpenVPN config file is located at $(pwd)"
fi 

if [ -n "$Gflag" ] && [ -n "$rflag" ] ; then
  keypath=$(pwd)
  if [ ! -f "$keypath/${region}_vpnkey.pem" ]; then
    echo -e  "${white}Generating new keypair for $region."
    generate_key=$(python keygen.py "${region}_vpnkey" "$region" "$keypath")
    [[ $generate_key == "Success" ]] || failed 1
    echo -e "${green}${region}_vpnkey has been created"
    ssh-add -l &>/dev/null
    if [ "$?" == 2 ]; then
      eval $(ssh-agent -s) &>/dev/null
    fi
    ssh-add "$keypath/${region}_vpnkey.pem" &>/dev/null
  elif [ -f "$keypath/${region}_vpnkey.pem" ]; then
    echo -e "${yellow}A Keypair for this region already exists."
  fi
  echo -e "${green}Use ${region}_vpnkey as keyname to create endpoint."
fi 

if [ -n "$Sflag" ] && [ -n "$rflag" ]  ; then
  get_status=$(python get_status.py "$region")
  echo -e "${green}Instances running in ${region}\n ${get_status}"
fi  

if [ -n "$Tflag" ] && [ -n "$rflag" ] && [ -n "$zflag" ]  ; then
   echo -e "${yellow}WARNING: instance ${term_ids} in ${region} will be terminated. This is not reversible"
   read -p "Are you sure you want to continue? y/n :" -n 1 -r
   if [[ $REPLY =~ ^[Yy]$ ]]; then
    termec2=$(python terminate.py "$region" "$term_ids")
    [[ $termec2 == "Success" ]] || failed 2
    echo -e "\n${green}${term_ids} has been terminated."
   elif [[ $REPLY =~ ^[Nn]$ ]]; then
    echo -e "\n${green}No instances were terminated."
  fi
fi 

if [ -n "$Dflag" ] && [ -n "$rflag" ] && [ -n "$kflag" ]  ; then
   echo -e "${yellow}WARNING: Keypair ${keyname} in ${region} will be deleted. This is not reversible"
   read -p "Are you sure you want to continue? y/n :" -n 1 -r
   if [[ $REPLY =~ ^[Yy]$ ]]; then
    delkey=$(python delete_key.py "$region" "$keyname")
    [[ $delkey == "Success" ]] || failed 3
    echo -e "\n${green}${keyname} has been deleted. Make sure to remove the .pem file on your box "
   elif [[ $REPLY =~ ^[Nn]$ ]]; then
    echo -e "\n${green}No keypairs were deleted."
  fi
fi
tput sgr0 